### ISSUE TITLE
Remove the run interface in operations.py

### ISSUE THREAD

**Issue by kidrahahjo** [glotzerlab/signac-flow#463] opened 2021-02-11 09:03 UTC
### Feature description
signac-flow now uses a project wise approach to handle the execution of operations. And due to this, I don't think that there is a requirement for the `run` interface we provide in `operations.py`. I propose to remove it. 

### Proposed solution
Since this is no longer a part of our core API, we can run a deprecation cycle of just a single version, or simply just remove it.

### Additional context
If we decide not to remove that interface, do we want to add support of aggregate operations to that?

**Comment by adgnabro** [comment] 2021-02-11 11:37
Hi ! I can help one this one.

**Comment by kidrahahjo** [comment] 2021-02-11 11:55
Hey @adgnabro, welcome!
Thank you for reaching out to us and we really appreciate you helping us out.

If @glotzerlab/signac-committers agree to resolve this issue by removing the feature, I'll be very happy to assign you this!

**Comment by vyasr** [comment] 2021-02-11 17:40
This is a duplicate of #221, but as we are moving towards a 1.0 release, I think it is a good time to revisit. I am in favor of moving forward with this deprecation. There were some arguments made on #221 for why we should keep it that I can summarize here in case anyone wants to argue for retaining this API in flow 1.0.

Removing this will not break any existing operations/project modules (keeping operations in a separate file from projects is and always will be supported), as long as `flow.run` is guarded by an `if __name__ == "__main__"` block, which I think is a reasonable assumption since otherwise that would have broken when importing operations into a project.py file. The main loss of functionality is direct execution via `python operations.py op job` of an operation function that has never been added to any `FlowProject`, which I think is both an extreme minor regression and out of scope for signac-flow. While the maintenance burden for `flow.run` is low, it has been a source of confusion for new users (and even more so for developers, even those who aren't that new) on multiple occasions, so I think we benefit from removing it in that respect as well.

**Comment by kidrahahjo** [comment] 2021-02-12 11:28
Sounds good! @adgnabro since @vyasr has agreed to deprecate the interface, you can start working on this issue.
Here is what you'll need to do.
1. Clone the repository
2. In `flow/operations.py`, deprecate the method `run`. Currently, we use the library `deprecation` to deprecate things in our code base. (You can see the way we deprecate things in `flow/project.py`)
3. Post a pull request

**Comment by adgnabro** [comment] 2021-02-16 13:57
Ok let's go ! Just a question. What is the purpose to use the library deprecation ? I could simply remove all the references of run method in the code right ?

**Comment by bdice** [comment] 2021-02-16 14:20
Good question @adgnabro! To minimize the impact of removing code from our public API, we notify users that certain features are deprecated. Then, we perform the removal in a later release. Without a deprecation period, users might upgrade and have their code break unexpectedly. You can see the deprecation policy here: https://docs.signac.io/projects/flow/en/latest/support.html#deprecation-policy

**Comment by vyasr** [comment] 2021-02-26 20:45
Addressed in #467.

**Closed by vyasr** 2021-02-26 20:45 UTC
Labels: good first issue
