### ISSUE TITLE
Proposal for improved execution flow

### ISSUE THREAD

**Issue by csadorf** [glotzerlab/signac-flow#30] opened 2018-07-20 14:34 UTC
**[Original report](https://bitbucket.org/glotzer/signac-flow/issue/30) by Mike Henry (Bitbucket: [mikemhenry](https://bitbucket.org/mikemhenry), GitHub: [mikemhenry](https://github.com/mikemhenry)).**

----------------------------------------

Let's use this issue to track ideas on how to add  some functionality to `signac-flow` that will keep jobs 'flowing'.

Few things to consider:

* Use the hostname to only run a subset of operations
* look at systemd or some sort of signaling type daemon to keep things moving along
* Talk with HPC admins to see what they think would be effective

**Comment by vyasr** [comment] 2019-07-05 15:44
@csadorf @mikemhenry I think we need to split this issue into well-defined tasks so that we can actually assign them and tackle them. Simon's last post is a good example of one such task, are there others?

**Comment by vyasr** [comment] 2020-02-26 17:03
@csadorf @mikemhenry any further thoughts on how we can split this into multiple issues? Otherwise I'd vote to close, it's too vague to be actionable.

**Comment by bdice** [comment] 2020-02-26 18:12
I would like to close this issue as well. I don't think this is as large of a pain point as we once thought. Groups offers some slight benefits to users needing an "eligibility by cluster" criterion, in a similar way to #33 (which was previously marked as a duplicate of this issue). @csadorf @mikemhenry feel free to re-open if you wish.

**Closed by bdice** 2020-02-26 18:12 UTC
Labels: enhancement, groups

**Comment by csadorf** [comment] 2020-02-26 18:35
I think this should be addressed by groups, which is why I labeled it as such.
