### ISSUE TITLE
flow load_config doesn't work with separate project directory from project.py

### ISSUE THREAD

**Issue by tommy-waltmann** [glotzerlab/signac-flow#196] opened 2019-12-13 16:25 UTC
### Description

Somehow, the monkey-patching of flow's config isn't working. It is supposed to ensure that a default value of 0.2 is applied for the key `status_performance_warn_threshold`. It's running into a problem on this line because the `warn_threshold` is `None`. https://github.com/glotzerlab/signac-flow/blob/893017073a9ce0203e03efbdcab75f094e2d6793/flow/project.py#L2666

### To reproduce

```python
>>> from flow.util import config
>>> config.get_config_value('status_performance_warn_threshold') is None
True
```

### Error output

```python
$ python project_training.py status
Using environment configuration: UnknownEnvironment
Collecting job status info: 100%|███████████████| 1/1 [00:00<00:00, 247.47it/s]

# Overview: 
Total # of jobs: 1 

label  ratio                                              
-----  -------------------------------------------------- 

operation     number of eligible jobs
------------  -----------------------
train_ml      1


ERROR: Encountered error during program execution: ''>' not supported between instances of 'float' and 'NoneType''
```

### System configuration

Please complete the following information:

 - Operating System [e.g. macOS]: Darwin-18.7.0-x86_64-i386-64bit
 - Version of Python [e.g. 3.7]: 3.6.7 | packaged by conda-forge | (default, Nov  6 2019, 16:03:31) [GCC Clang 9.0.0 (tags/RELEASE_900/final)]
 - Version of signac [e.g. 1.0]: 1.2.0
 - Version of signac-flow: 0.8.0 (latest master)

**Comment by bdice** [comment] 2019-12-20 00:08
@tommy-waltmann and I dug into this further today. The actual problem is that we're using a signac project that is in a different directory than `project.py`. This causes `flow.util.config.load_config()` to fail -- it doesn't find the project's config properly.

The monkey patch is working fine, so I'll rename this issue accordingly.

**Comment by bdice** [comment] 2019-12-21 20:21
## Context

The core `signac` package uses config values that correspond to the data space itself (e.g. project id, workspace directory). The `flow` package uses config values that don't really have anything to do with the data space itself (e.g. account names for submission, status output settings). When running a `FlowProject` from a different directory than the signac project, this causes some dissonance. I often keep my source code (e.g. project operations) in a git repository that is separate from the signac data space. I use `FlowProject.get_project('/path/to/project')` to create my `FlowProject` instance, where the project path is usually a symlink to network storage or a scratch directory.

Below, I am documenting the current use cases of config values in `flow`.

## Places in the codebase where flow config values are used:

- (Original function definition)
```
flow/util/config.py
28:def require_config_value(key, ns=None, default=_GET_CONFIG_VALUE_NONE):
54:def get_config_value(key, ns=None, default=None):
```

- In `ComputeEnvironment.get_config_value`, which is used in templates to do things like provide account names. The function name `get_config_value` exists twice. Once in `flow.util.config.get_config_value` and again as a class method in `flow.environment.ComputeEnvironment.get_config_value` (which confusingly uses `flow.util.config.require_config_value` instead of `flow.util.config.get_config_value`).
```
flow/environment.py
168:    def get_config_value(cls, key, default=flow_config._GET_CONFIG_VALUE_NONE):
192:        return flow_config.require_config_value(key, ns=cls.__name__, default=default)
```

- When defining template filters:
```
flow/project.py
651:        template_environment.filters['get_config_value'] = flow_config.get_config_value
652:        template_environment.filters['require_config_value'] = \
653:            flow_config.require_config_value
```

- In template filter `get_account_name`:
```
flow/util/template_filters.py
9:from .config import require_config_value
190:        return require_config_value('account', ns=environment)
```

- On `import flow`, config values are used to determine whether to import packaged environments.
```
flow/__init__.py
31:from .util.config import get_config_value
32:if get_config_value('import_packaged_environments', default=True):
```

- These are all configuration values for printing more or less verbosely.
```
flow/project.py
1178:            eligible_jobs_max_lines = flow_config.get_config_value('eligible_jobs_max_lines')
2665:            warn_threshold = flow_config.get_config_value(config_key)
2982:        if flow_config.get_config_value('show_traceback'):
```

- The method is tested:
```
tests/test_environment.py
22:    def test_environment_get_config_value(self):
27:                a = env.get_config_value('a')
29:        a = env.get_config_value('a', None)
32:        a = env.get_config_value('a', 42)
```

- One template for flux (the cluster is no longer operational) uses the `get_config_value`:
```
flow/templates/umich-flux.sh
26:{% set qos = 'qos'|get_config_value(environment, 'flux') %}
28:{% set queue = 'cpu_queue'|get_config_value(environment, 'flux') %}
```

**Comment by bdice** [comment] 2020-01-07 18:41
For now, we got around this problem by adding a `signac.rc` file in the directory of `project.py` containing:
```
[flow]
status_performance_warn_threshold=0.2
```

**Comment by vyasr** [comment] 2020-02-26 17:28
@bdice is this an issue we should be addressing, or can we close it? You can always create a `FlowProject` in Python that uses a specific config file somewhere. I'm not quite clear on how you are currently indicating to flow where the signac.rc file is if you keep your project.py file in a separate directory (without specifying the config).

**Comment by bdice** [comment] 2020-02-26 17:59
I need to do a little bit of testing to determine what should be done, if anything. I'll follow up on this at a future sprint, it's low priority but should be easy to fix once I determine what to do.

**Comment by bdice** [comment] 2020-04-11 15:39
This seems to be solved. I'm not sure what changed, but I can't reproduce the issue now.

**Closed by bdice** 2020-04-11 15:39 UTC
Labels: bug
