### ISSUE TITLE
Broken backwards-compatibility: walltime conversion

### ISSUE THREAD

**Issue by tcmoore3** [glotzerlab/signac-flow#295] opened 2020-06-15 14:38 UTC
### Description

A concise description of what is causing an issue and what you expected to happen.

To prevent my jobs from running too long on the cluster and exiting cleanly, I usually set some environment variables with variables from the flow template. I get the total walltime (in seconds) via
`export WT={{ walltime*3600 }}`.

On `master`, (commit `7721966094419`), where support for `GreatLakesEnvironment` has been added, this functionality does not work. That expression gets evaluated to `3000 days, 0:00:00`, which is 3600x the length that I want to set (i.e., walltime is already in seconds in the template whereas it should be in hours).

I can get the old behavior back by using `export WT={{ walltime.seconds }}`.

### System configuration

This is on Great Lakes.

```
 $ python -c 'import platform; print(platform.platform()); import sys; print(sys.version); import signac; print(signac.__version__); import flow; print(flow.__version__)'
Linux-3.10.0-1062.9.1.el7.x86_64-x86_64-with-glibc2.10
3.8.3 | packaged by conda-forge | (default, Jun  1 2020, 17:43:00) 
[GCC 7.5.0]
1.4.
```

**Comment by b-butler** [comment] 2020-08-20 15:59
@tcmoore3 noticed this as well, but I can't seem to find what caused this change when looking at the repository history. I don't see any changes in Python's `datetime` module either. I an not sure how many others use the walltime in a way that will break. I will leave this open for now without a `wontfix` label, but I am not sure that this will be fixed or restored.

**Comment by bdice** [comment] 2020-08-21 04:58
Hmm. I am not sure of the cause but this bug should be carefully addressed when handling #240.

**Comment by vyasr** [comment] 2020-09-16 16:00
@bdice @b-butler @tcmoore3 I haven't spent any time trying to isolate the change that caused this, but I'm wondering if we should consider this a feature rather than a bug. The walltime is clearly being converted to either a `datetime.datetime` or a `datetime.timedelta` object (I don't remember which one has the particular string representation that Tim's post shows), and that's a pretty rich object that could end up being more useful than just a single number in the context of an arbitrary template script.

Unrelated @tcmoore3 the object is a `datetime.timedelta` then I think you have to request `total_seconds` rather than `seconds`; you may have gotten lucky since it looks like your original walltime was < 24 hours (looks like 20 hours from the math), but if it's a timedelta and you specify like 25 hours then `seconds` will only give you `3600` rather than the `90000` you'd get from `total_seconds`. `seconds` only gives times less than 24 hours, the remainder gets lumped into `days`.

**Comment by kidrahahjo** [comment] 2021-01-26 15:25
@vyasr @bdice @tcmoore3 Is this addressed?

**Comment by vyasr** [comment] 2021-01-26 19:13
I'm not convinced that we should change anything here. At this point the breaking change has persisted for a while, and the new behavior is probably preferable in the long term anyway.

**Comment by bdice** [comment] 2021-01-26 19:22
I agree that the `datetime` object is correct, and it's [documented in the submit API](https://github.com/glotzerlab/signac-flow/blob/8a079538b5986f69b209bd4214ead74f96d10c99/flow/project.py#L3829-L3831). However, I don't like our implementation of how `walltime` is handled. It should perform an `isinstance(walltime, datetime.timedelta)` and then proceed to handle it as "hours-like". https://github.com/glotzerlab/signac-flow/blob/8a079538b5986f69b209bd4214ead74f96d10c99/flow/project.py#L3860-L3868

**Comment by vyasr** [comment] 2021-01-26 19:57
This looks like a straight up bug. The API promises to support timedelta objects, but you can't create one timedelta from another. This really should be a no-op if `isinstance(walltime, datetime.timedelta)`.

**Closed** 2021-03-17 01:49 UTC
Labels: bug
