### ISSUE TITLE
mpi prefix not included with groups

### ISSUE THREAD

**Issue by atravitz** [glotzerlab/signac-flow#300] opened 2020-06-19 23:10 UTC
### Description
When submitting a multi-gpu (or cpu) job, flow does not include the `mpirun -np {n_nodes}` prefix.  

### To reproduce

I've tried submitting jobs with the directive `ngpu=2` (or any value >1), and the test script looks as follows:
```python
#!/bin/bash
#SBATCH --job-name="bridgingDyna/3ad2e1ee/sample/0000/78df544387c5991e5e8868c06d0625e3"
#SBATCH --partition=gpu
#SBATCH --mem=4g
#SBATCH -t 02:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=2
#SBATCH --gpus=2
#SBATCH --account=rlarson1

set -e
set -u

cd /gpfs/accounts/rlarson_root/rlarson/atravitz/bridging_kinetics

# sample(3ad2e1eeea83687a06a156777958630d)
/home/atravitz/miniconda3/envs/alyssa/bin/python /gpfs/accounts/rlarson_root/rlarson/atravitz/bridging_kinetics/project.py run -o sample -j 3ad2e1eeea83687a06a156777958630d --debug
# Eligible to run:
# /home/atravitz/miniconda3/envs/alyssa/bin/python /gpfs/accounts/rlarson_root/rlarson/atravitz/bridging_kinetics/project.py exec sample 3ad2e1eeea83687a06a156777958630d
```

I only get two gpus when I add `mpirun -np 2` as the prefix.

### System configuration

Please complete the following information:

 - Operating System [e.g. macOS]: this is on Great Lakes
 - Version of Python [e.g. 3.7]: 3.7.6
 - Version of signac [e.g. 1.0]: 1.2.0
 - Version of signac-flow:0.9.0

Or copy & paste the output of: `python -c 'import platform; print(platform.platform()); import sys; print(sys.version); import signac; print(signac.__version__); import flow; print(flow.__version__)'`

**Comment by vyasr** [comment] 2020-06-20 18:32
Partial duplicate of #296

**Comment by atravitz** [comment] 2020-06-22 16:47
to address @b-butler's question about adding `nranks`, this is my output when i pass `ngpu=2, nranks=2`: 

```python
Submitting cluster job 'bridgingDyna/768dfc2f/sample/0000/9b20f93ff6dc8d5cd77de3357baf5630':
 - Group: sample(768dfc2f6a5b3ddcf4383c7083bdf6f3)
WARNING:flow.project:Some of the keys provided as part of the directives were not used by the template script, including: nranks, omp_num_threads
#!/bin/bash
#SBATCH --job-name="bridgingDyna/768dfc2f/sample/0000/9b20f93ff6dc8d5cd77de3357baf5630"
#SBATCH --partition=gpu
#SBATCH --mem=4g
#SBATCH -t 24:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=2
#SBATCH --gpus=2
#SBATCH --account=rlarson1

set -e
set -u

cd /gpfs/accounts/rlarson_root/rlarson/atravitz/bridging_kinetics

# sample(768dfc2f6a5b3ddcf4383c7083bdf6f3)
/home/atravitz/miniconda3/envs/alyssa/bin/python /gpfs/accounts/rlarson_root/rlarson/atravitz/bridging_kinetics/project.py run -o sample -j 768dfc2f6a5b3ddcf4383c7083bdf6f3
# Eligible to run:
# /home/atravitz/miniconda3/envs/alyssa/bin/python /gpfs/accounts/rlarson_root/rlarson/atravitz/bridging_kinetics/project.py exec sample 768dfc2f6a5b3ddcf4383c7083bdf6f3
```

**Comment by b-butler** [comment] 2020-06-22 16:56
I didn't expect the MPI command to show up here. I am more curious if it will use it internally. I believe it will (i.e. it will run with MPI, just not submit with it).

**Comment by atravitz** [comment] 2020-06-22 22:18
I think it does use it internally if I pass in `nranks` (HOOMD is now running on multiple gpus), how can I check this explicitly? 

Also the warning message `WARNING:flow.project:Some of the keys provided as part of the directives were not used by the template script, including: nranks, omp_num_threads` still comes up, which is misleading since it clearly *is* using `nranks`.

**Comment by csadorf** [comment] 2020-06-23 08:25
> I didn't expect the MPI command to show up here. I am more curious if it will use it internally. I believe it will (i.e. it will run with MPI, just not submit with it).

Why not? I thought the point of these comments was to be able to see what exactly is expected to be executed?

**Comment by vyasr** [comment] 2020-06-23 14:23
@csadorf I think @b-butler was referring to how he expected the current version of the code to behave (specifying nranks and ngpu should result in the correct behavior of using `mpirun` at run time during a submission, but the printed pretend output won't include the MPI command), not how we want this to behave in an ideal case (including `mpirun` in the printed pretend output). Fixing this is what we were discussing in the meeting yesterday.

**Comment by b-butler** [comment] 2020-06-23 19:15
@csadorf I meant exactly what Vyas mentioned.

**Comment by b-butler** [comment] 2020-06-23 19:17
Also, the warnings have to do with template not directly using `nranks` or `omp_num_threads` any more, but they are always set to a default value now.

**Comment by vyasr** [comment] 2020-06-23 19:24
Right, the groups changes break the `TrackGetItemDict` solution that we were using to determine what keys are used in the script. Unless there's an easy way to change the provision of defaults by groups, I think we should simply disable the warnings provided by that code path for the next minor release. While not ideal, since it's just a warning that's no longer provided I think that's an acceptable temporary regression to avoid delaying a release any further than necessary.

**Closed** 2020-06-25 21:29 UTC
