### ISSUE TITLE
Executable path links to the local environment when generating template reference data

### ISSUE THREAD

**Issue by kidrahahjo** [glotzerlab/signac-flow#398] opened 2020-12-11 04:57 UTC
### Description
In generate_template_reference_data.py we have a method called get_masked_flowproject which we use to create the project. There, we mock `sys.executable` before instantiating the project.

It seems like this is a problem related to the `directives` module. We initialize _EXECUTABLE in that module with the default value of `sys.executable`. I think that value is stored before we mock `sys.executable` hence the default value of an executable path always refers to the local environment.

### To reproduce
Execute 
`python -f test/generate_template_reference_data.py`
And test it with
`pytest test/test_templates.py`

### Possible Solution
Reset default value of the `_EXECUATABLE` variable to `sys.executable` when we return the default values of all the directives in `environment.py`
@glotzerlab/signac-maintainers please weigh in.

PS. thanks to @ramanishsingh for pushing a PR, that way I got to learn about this problem.

**Comment by bdice** [comment] 2020-12-11 05:16
I accidentally overwrote a commit from @ramanishsingh on #393 that was a proposed solution for this problem. I'm copying it here as a starting point for a solution, though I haven't evaluated it myself. https://github.com/glotzerlab/signac-flow/commit/8eb5b370048556a284fc51ce76b0506b03847dd4

```diff
diff --git a/flow/environment.py b/flow/environment.py
index dc5ea070..e2974da2 100644
--- a/flow/environment.py
+++ b/flow/environment.py
@@ -274,6 +274,8 @@ def get_prefix(cls, operation, parallel=False, mpi_prefix=None, cmd_prefix=None)
 
     @classmethod
     def _get_default_directives(cls):
+        import sys
+        _EXECUTABLE._default = sys.executable
         return _Directives(
             [
                 _NP,
```

**Comment by kidrahahjo** [comment] 2020-12-11 05:34
@bdice actually I suggested @ramanishsingh to try that solution out and it was working fine. For me, the `_EXECUTABLE` directive is the most obvious candidate which needs to get fixed.

**Comment by vyasr** [comment] 2020-12-15 13:43
@kidrahahjo I agree that `_EXECUTABLE` is what needs to get modified. However, I think that there is a potential scoping problem with your proposed change. It leads to a modification of `_EXECUTABLE` in the global namespace, which will propagate to any future processes that are run and seems likely to result in similar problems down the road if we modify any of these scripts in other ways that rely on `_EXECUTABLE` behaving normally, for instance if for some reason we need to generate a non-masked `FlowProject`.

It seems to me that the underlying problem is that we should always be evaluating the executable at call-time (when `_EXECUTABLE` is used) rather than at definition time (at the top of`directives.py` where `_EXECUTABLE` is defined). If that is true, then I would prefer to redefine `_EXECUTABLE` using a nullary lambda that acquires the executable on-the-fly:
```
_GET_EXECUTABLE = lambda: _Directive(
    'executable', validator=_OnlyType(str), default=sys.executable,
    serial=_no_aggregation, parallel=_no_aggregation)
```

Alternatively, since `_get_default_directives` seems to be the only place that the "commonly used directives" defined as module-level constants in `directives.py` are used, you could also inline this, but for consistency the lambda might be the most reproducible change.

**Comment by kidrahahjo** [comment] 2020-12-16 05:08
This seems like a more reasonable solution. I also felt that my solution was a little bit hacky in nature. Thanks @vyasr, I will push the changes and request reviews.

**Comment by bdice** [comment] 2021-01-13 05:39
This is solved on `next`. I'm closing this issue to reduce clutter.

**Closed by bdice** 2021-01-13 05:39 UTC
