### ISSUE TITLE
Bundling in parallel for RM partition in Bridges 2 uses single core out of 128

### ISSUE THREAD

**Issue by syjlee** [glotzerlab/signac-flow#583] opened 2021-11-09 20:44 UTC
### Description
I noticed bundling in parallel in RM node ends up with parallelizing in a core, not in a node.

### To reproduce

python project.py submit --partition=RM --bundle=128 --parallel

### submission output

```# Submit command: sbatch
#!/bin/bash
#SBATCH --job-name="test-bundle/bundle/d3fd89cb4b3414467ddb52232e04b9fe63006f00"
#SBATCH --partition=RM
#SBATCH -t 06:00:00
#SBATCH -N 1
#SBATCH --ntasks-per-node=128
#SBATCH -A dmr170059p

set -e
set -u

cd /ocean/projects/dmr170059p/syjlee/2Dsingle_rigidrod/bundle-test

# run(83829238988e4ac235231c6c863c94f4)
/jet/home/syjlee/miniconda3/bin/python /ocean/projects/dmr170059p/syjlee/2Dsingle_rigidrod/bundle-test/project3.py run -o run -j 83829238988e4ac235231c6c863c94f4 &
# Eligible to run:
# singularity exec /ocean/projects/dmr170059p/syjlee/software3.sif python /ocean/projects/dmr170059p/syjlee/2Dsingle_rigidrod/bundle-test/project3.py exec run 83829238988e4ac235231c6c863c94f4

# run(5320829ea1d4b1610d0aaa433a61efa2)
/jet/home/syjlee/miniconda3/bin/python /ocean/projects/dmr170059p/syjlee/2Dsingle_rigidrod/bundle-test/project3.py run -o run -j 5320829ea1d4b1610d0aaa433a61efa2 &
# Eligible to run:
# singularity exec /ocean/projects/dmr170059p/syjlee/software3.sif python /ocean/projects/dmr170059p/syjlee/2Dsingle_rigidrod/bundle-test/project3.py exec run 5320829ea1d4b1610d0aaa433a61efa2

... same for the rest of 126
```

I'm attaching htop result indicating that one core is in use. 

![Screen Shot 2021-11-09 at 2 51 55 PM](https://user-images.githubusercontent.com/44685431/141001339-62be3fd2-094e-4eb2-b87b-09db7699e914.png)

Also, minimal running code:
```
import signac
import flow
from flow import aggregator, directives

class Project(flow.FlowProject):
    pass

@Project.label
def sampled(job):
    return job.doc['current_timestep'] == (job.doc.total_time/job.doc.dt)

@Project.post(sampled)
@Project.operation.with_directives({"walltime": 6, "np":1, "executable": "singularity exec /ocean/projects/dmr170059p/syjlee/software3.sif python"})
def run(job):
    import gsd
    import gsd.hoomd
    import freud

    import numpy as np

    import hoomd
    import hoomd.md

    with job:
        # Save init.gsd
        with gsd.hoomd.open(name='init.gsd', mode='wb') as f:
            f.append(s)

        # Create simulation object
        random.seed()
        device = hoomd.device.CPU()
        sim = hoomd.Simulation(device=device, seed=random.randint(1,1000))
        sim.create_state_from_gsd(filename='init.gsd')

        sim.run(total_timesteps)

        job.doc['current_timestep'] = sim.timestep


if __name__ == '__main__':
    Project().main()
```

### System configuration

Please complete the following information:

 - Operating System [e.g. macOS]: Linux-4.18.0-193.28.1.el8_2.x86_64-x86_64-with-glibc2.10
 - Version of Python [e.g. 3.7]: 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 16:22:27) [GCC 9.3.0]
 - Version of signac [e.g. 1.0]: 1.7.0
 - Version of signac-flow: 0.16.0

Or copy & paste the output of: `python -c 'import platform; print(platform.platform()); import sys; print(sys.version); import signac; print(signac.__version__); import flow; print(flow.__version__)'`

**Comment by b-butler** [comment] 2021-11-11 03:18
I ran an interactive job on Bridges2 and just running `singularity exec ...` utilized multiple cores, so I am not immediately sure what the problem is. I will have to do a deeper dive later.

**Comment by b-butler** [comment] 2021-11-16 20:03
@syjlee, I don't think this is a `flow` problem. I ran a simple project using `time.sleep(10)`, and `--bundle --parallel` and just `--bundle` and found the expected behavior. The code is
```python
from time import sleep
import flow

class Project(flow.FlowProject):
    pass

@Project.operation
def calc(job):
    sleep(10)

if __name__ == "__main__":
    Project().main()
```
and the submission script looks like (in the parallel case),
```shell
# Submit command: sbatch
#!/bin/bash
#SBATCH --job-name="Test/bundle/7c37014ca2c407b5ce211c48c543edd4981f0cbe"
#SBATCH --partition=RM-shared
#SBATCH -N 1
#SBATCH --ntasks=5
#SBATCH -A PROJECT_ACCOUNT

set -e
set -u

cd $HOME

# calc(2af7905ebe91ada597a8d4bb91a1c0fc)
python $HOME/tmp-projec//project.py run -o calc -j 2af7905ebe91ada597a8d4bb91a1c0fc &
# Eligible to run:
# python $HOME/tmp-project/project.py exec calc 2af7905ebe91ada597a8d4bb91a1c0fc
# ...
wait

**Comment by b-butler** [comment] 2021-11-16 21:15
After adding this operation,
```python
@Project.operation
  def expensive_calc(job):
      for _ in range(1_000_000):
          a = sum(i for i in range(1_000_000))
```

and using the following for loop in an interactive job
```shell
for workspace in workspace/*; do                                                                                                                                                                                                                                                         
    python project.py run -o expensive_calc -j "${workspace#workspace/}" &
done
```
runs on all cores as shown by top (each process utilizing 100% of a CPU).

**Comment by syjlee** [comment] 2021-11-17 17:14
From a re-test of bundling jobs, bundled jobs are running fine on multiple cores in `RM-shared`. But `RM` node still gives bundled jobs running parallel in a single core. Until further investigation, it's encouraged to submit jobs bundled parallel to `RM-shared`.

**Comment by b-butler** [comment] 2022-12-12 20:35
Closing issue now. This is not a flow error but due to the way cores are pinned or not on certain clusters.

**Closed by b-butler** 2022-12-12 20:35 UTC
Labels: bug, cluster submission
